import 'product.dart';

class Myproducts {
  static List<Product> allbooks = [
    Product(
        id: 1,
        name: 'THE REVENANT',
        price: 900,
        category: 'NOVEL',
        image: 'assets/books/revenant.jpg',
        description:
            " A thrilling tale of betrayal and revenge set against the nineteenth-century American frontier, Michael Punke's The Revenant is the astonishing story of real-life trapper and frontiersman Hugh Glass. The year is 1823, and the trappers of the Rocky Mountain Fur Company live a brutalfrontier life.",
        quantity: 1,
        doc_title: 'THE revanent',
        doc_url: "https://www.docdroid.net/j9mg/revenant-pdf#page=16",
        doc_date: '9-10-2024',
        page_num: 1),
    Product(
      id: 18,
      name: 'G O T',
      price: 800,
      category: 'NOVEL',
      image: 'assets/books/got.jpg',
      description:
          "A Game of Thrones takes place over the course of one year on or near the fictional continent of Westeros. The story begins when King Robert visits the northern castle Winterfell to ask Ned Stark to be his right-hand assistant, or Hand of the King. The previous Hand, Jon Arryn, died under suspicious circumstances.",
      quantity: 1,
      doc_title: 'Game Of Thrones',
      doc_url:
          "https://www.nothuman.net/images/files/discussion/1/e72f9f1f181a66887baa7270037c582e.pdf",
      doc_date: '09-1-2003',
      page_num: 1,
    ),
    Product(
        id: 7,
        name: 'TANGLED',
        price: 700,
        category: 'ADVENTURE',
        image: 'assets/books/tangled1.jpg',
        description:
            "Rapunzel has spent her life locked in a tower, but that's not her only secret. Her long, golden hair has magical powers--all 70 feet of it! When the kingdom's most-wanted bandit unexpectedly stumbles into Rapunzel's tower, the pair embark on a fantastic journey that will uncover more than they ever expected.",
        quantity: 2,
        doc_title: 'Tangled',
        doc_url: "https://fliphtml5.com/ciykm/ysem/basic',doc_date: '1-25-1999",
        doc_date: '6-09-9999',
        page_num: 1),
    Product(
        id: 3,
        name: 'IT',
        price: 600,
        category: 'HORROR',
        image: 'assets/books/it1.jpg',
        description:
            "It is a horror novel by Stephen King about seven adults who return to their hometown to battle an evil creature that they first encountered as teenagers:",
        quantity: 3,
        doc_title: 'It',
        doc_url:
            'https://englishonlineclub.com/pdf/Stephen%20King%20-%20It%20%5BEnglishOnlineClub.com%5D.pdf',
        doc_date: '11-2-2011',
        page_num: 1),
    Product(
        id: 4,
        name: 'INTERESTELLAR',
        price: 500,
        category: 'SCIENTIFIC',
        image: 'assets/books/interest.jpg',
        description:
            "Interstellar is a Christopher Nolan movie exploring the vast galaxy through a time and space paradox. The movie primarily focuses on life. Earth is coming to an end and a few astronauts are traveling to find another home at the end of the galaxy.",
        quantity: 1,
        doc_title: 'Interestellr',
        doc_url:
            "https://static1.squarespace.com/static/5a1c2452268b96d901cd3471/t/5b95b7b0032be4f0cd3a8db2/1536538544682/Interstallar.pdf",
        doc_date: '12-2-2054',
        page_num: 1),
    Product(
        id: 5,
        name: 'THE MATRIX',
        price: 400,
        category: 'NOVEL',
        image: 'assets/books/matrix1.jpg',
        description:
            "Groff's fourth novel, Matrix is about a seventeen-year-old Marie de France... sent to England to be the new prioress of an impoverished abbey, its nuns on the brink of starvation and beset by disease. Alex Preston, writing in The Observer, described it as a strange and poetic piece of historical fiction set in a dreamlike abbey, the fictional biography of a 12th-century mystic. Within the novel, Marie, whom Groff writes as a lesbian, turns around the abbey's fortunes and treats it as a quasi-mystical female separatist utopia",
        quantity: 1,
        doc_title: 'the matrix',
        doc_url: "https://www.dailyscript.com/scripts/the_matrix.pdf",
        doc_date: '12-12-2092',
        page_num: 1),
    Product(
        id: 6,
        name: 'BRAIN ON FIRE',
        price: 900,
        category: 'MYSTERY',
        image: 'assets/books/fire.jpg',
        description:
            "Brain on Fire: My Month of Madness is a 2012 New York Times best-selling autobiography by New York Post writer Susannah Cahalan. The book details Cahalan's struggle with a rare form of encephalitis and her recovery.",
        quantity: 1,
        doc_title: 'brain on fire',
        doc_url: "https://static.booktopia.com.au/pdf/9781846147746-1.pdf",
        doc_date: '13-11-2026',
        page_num: 1),
    Product(
        id: 16,
        name: 'MOTHER EARTH',
        price: 708,
        category: 'GENERIC',
        image: 'assets/books/earth1.jpg',
        description:
            "He explains how the earth was built from cosmic dust and transformed into continents, oceans, atmosphere, and life. We find out why earth was primed for life and the many ways it could have started. We learn how minerals and living organisms evolved together shaping the future of each other.",
        quantity: 3,
        doc_title: 'mother earth',
        doc_url:
            "https://www.arvindguptatoys.com/arvindgupta/aitmatov-motherearth.pdf",
        doc_date: '15-6-3022',
        page_num: 1),
    Product(
        id: 8,
        name: 'MAHABHARATHAM ',
        price: 1000,
        category: 'MYTHOLOGY',
        image: 'assets/books/Mahabharata.jpg',
        description:
            "The Mahabharata is an ancient Indian epic poem that is considered one of the most important texts in world literature. It is a narrative of the Kurukshetra War, a conflict between two groups of cousins, the Pandavas and the Kauravas, over the throne of Hastinapura. The epic also includes philosophical and devotional material, such as the Bhagavad Gita, and is considered a source of information on the development of Hinduism.",
        quantity: 1,
        doc_title: 'mahabharathham',
        doc_url:
            "https://www.hariomgroup.org/hariombooks_shastra/mahabharata.pdf",
        doc_date: '15-9-2007',
        page_num: 1),
    Product(
        id: 9,
        name: 'WORLD WAR II',
        price: 955,
        category: 'HISTORY',
        image: 'assets/books/world.jpg',
        description:
            "The Second World War is a 2012 narrative history of World War II by the British historian Antony Beevor. The book starts with the Japanese invasion of Manchuria in 1931, and covers the entire Second World War. It ends with the final surrender of Axis forces.",
        quantity: 1,
        doc_title: 'world war 2',
        doc_url: "https://www.drishtiias.com/pdf/1594383154-world-war-ii.pdf",
        doc_date: '16-04-2001',
        page_num: 1),
    Product(
        id: 10,
        name: 'THE EXORIST',
        price: 855,
        category: 'NOVEL',
        image: 'assets/books/exorist1.jpg',
        description:
            "The Exorcist is a 1971 horror novel written by American writer William Peter Blatty and published by Harper & Row. The book details the demonic possession of eleven-year-old Regan MacNeil, the daughter of a famous actress, and the two priests who attempt to exorcise the demon.",
        quantity: 2,
        doc_title: 'the exorist',
        doc_url: "https://www.geocities.ws/thebookstore/the%20exorcist.pdf",
        doc_date: '10-16-2042',
        page_num: 1),
    Product(
        id: 11,
        name: 'COCO',
        category: 'STORY',
        price: 100,
        image: 'assets/books/coco.jpg',
        description:
            'a 12-year-old Mexican boy named Miguel who journeys to the Land of the Dead to find his great-great grandfather, Ernesto de la Cruz, a legendary sing',
        quantity: 1,
        doc_title: 'coco',
        doc_url:
            "https://images.southmountaincc.edu/WebImages/cdn/hs/f-23/Montano-frankie.pdf",
        doc_date: '19-05-2004',
        page_num: 1),
    Product(
        id: 12,
        name: 'DRAGON',
        category: 'anime',
        price: 10,
        image: 'assets/books/dragon.jpg',
        description:
            'How to Train Your Dragon is a 2010 film about a young Viking who befriends a dragon instead of killing it',
        quantity: 2,
        doc_title: 'how to train your dragon',
        doc_url:
            "https://pubhtml5.com/hmeo/xzqi/The_Art_of_How_to_Train_Your_Dragon/",
        doc_date: '19-6-2005',
        page_num: 1),
    Product(
        id: 13,
        name: 'GOD OF WAR',
        category: 'story game',
        price: 5000,
        image: 'assets/books/god.jpg',
        description:
            'God of War Ragnarök is an action-adventure game where players take the role of Kratos and his son as they embark on a quest to prevent the coming of Ragnarök. Players explore the Nine Realms, battling enemies in close-up, hand-to-hand combat against human-like raiders and fantastical creatures.',
        quantity: 1,
        doc_title: 'god of war',
        doc_url: "https://fliphtml5.com/uvite/nhtg/basic",
        doc_date: '18-06-2044',
        page_num: 1),
    Product(
        id: 14,
        name: 'MOANA',
        category: 'story',
        price: 50,
        image: 'assets/books/moana.jpg',
        description:
            'As described by Gramma Tala, Moana "stands out from the crowd". She is sea-loving, headstrong, strong-willed, practically fearless, and physically capable. Though she has moments of self-doubt, she has great pride in who she is, and is generally too stubborn to back away from new challenges.',
        quantity: 1,
        doc_title: 'Moana',
        doc_url:
            "https://cloud-6.edupage.org/cloud/moana.pdf?z%3A04IOxMwhEEmPu%2FFN1ysIL66jwbHOwauF8RiyoPz7k%2FM0q7X8gGUm6h%2BrNrBBeHC7",
        doc_date: '15-7-2003',
        page_num: 1),
    Product(
        id: 15,
        name: 'SHERK',
        category: 'anime',
        price: 80,
        image: 'assets/books/sherk.jpg',
        description:
            'Shrek is an anti-social and highly territorial ogre who loves the solitude of his swamp and enjoys fending off mobs and intruders. His life is interrupted after the dwarfish Lord Farquaad of Duloc exiles a vast number of fairy-tale creatures, who inadvertently end up in the swamp.',
        quantity: 1,
        doc_title: 'sherk',
        doc_url: "https://fliphtml5.com/rxmc/kptg/basic",
        doc_date: '1-04-2009',
        page_num: 1),
    Product(
        id: 2,
        name: 'UP',
        category: 'anime',
        price: 400,
        image: 'assets/books/up.jpg',
        description:
            'The film centers on Carl Fredricksen (Asner), an elderly widower who travels to South America with youngster Russell (Nagai) in order to fulfill a promise that he made to his late wife Ellie. In the jungle, they encounter an exotic bird and discover someone has sinister plans to capture it',
        quantity: 1,
        doc_title: 'up',
        doc_url:
            "https://blogs.glowscotland.org.uk/nl/public/cnhsenglish/uploads/sites/35490/2020/03/19120656/UP.pdf",
        doc_date: '10-5-2003',
        page_num: 1),
    Product(
        id: 17,
        name: 'WALL-E',
        category: 'story',
        price: 200,
        image: 'assets/books/wall.jpg',
        description:
            'Mesmerized with trinkets of Earths history and show tunes, WALL-E is alone on Earth except for a sprightly pet cockroach. One day, EVE, a sleek (and dangerous) reconnaissance robot, is sent to Earth to find proof that life is once again sustainable. WALL-E falls in love with EVE.',
        quantity: 1,
        doc_title: 'wall e',
        doc_url:
            "https://puyanama.com/wp-content/uploads/The%20Art%20of%20WallE_Puyanama.pdf",
        doc_date: '1-9-2011',
        page_num: 1),
  ];

  static List<Product> trendingbooks = [
    // Product(id: 1, name: 'THE REVENANT',price: 590, category: 'NOVEL', image: 'assets/books/revenant.jpg', description: " A thrilling tale of betrayal and revenge set against the nineteenth-century American frontier, Michael Punke's The Revenant is the astonishing story of real-life trapper and frontiersman Hugh Glass. The year is 1823, and the trappers of the Rocky Mountain Fur Company live a brutalfrontier life.", quantity: 1,),
    Product(
        id: 1,
        name: 'GOD OF WAR',
        category: 'story game',
        price: 5000,
        image: 'assets/books/god.jpg',
        description:
            'God of War Ragnarök is an action-adventure game where players take the role of Kratos and his son as they embark on a quest to prevent the coming of Ragnarök. Players explore the Nine Realms, battling enemies in close-up, hand-to-hand combat against human-like raiders and fantastical creatures.',
        quantity: 1,
        doc_title: 'god of war',
        doc_url: 'https://fliphtml5.com/uvite/nhtg/basic',
        doc_date: '10-2-2003',
        page_num: 1),
    Product(
        id: 4,
        name: 'G O T',
        price: 2000,
        category: 'NOVEL',
        image: 'assets/books/got.jpg',
        description:
            "A Game of Thrones takes place over the course of one year on or near the fictional continent of Westeros. The story begins when King Robert visits the northern castle Winterfell to ask Ned Stark to be his right-hand assistant, or Hand of the King. The previous Hand, Jon Arryn, died under suspicious circumstances.",
        quantity: 1,
        doc_title: 'g o t',
        doc_url: '',
        doc_date: '12-2-2032',
        page_num: 1),
    Product(
        id: 15,
        name: 'TANGLED',
        price: 600,
        category: 'ADVENTURE',
        image: 'assets/books/tangled1.jpg',
        description:
            "Rapunzel has spent her life locked in a tower, but that's not her only secret. Her long, golden hair has magical powers--all 70 feet of it! When the kingdom's most-wanted bandit unexpectedly stumbles into Rapunzel's tower, the pair embark on a fantastic journey that will uncover more than they ever expected.",
        quantity: 2,
        doc_title: 'tangled',
        doc_url: '',
        doc_date: '1-02-2032',
        page_num: 1),
    Product(
        id: 3,
        name: 'IT',
        price: 400,
        category: 'HORROR',
        image: 'assets/books/it1.jpg',
        description:
            "It is a horror novel by Stephen King about seven adults who return to their hometown to battle an evil creature that they first encountered as teenagers:",
        quantity: 3,
        doc_title: 'it',
        doc_url: '',
        doc_date: '1-14-2004',
        page_num: 1),
    Product(
        id: 11,
        name: 'INTERESTELLAR',
        price: 890,
        category: 'SCIENTIFIC',
        image: 'assets/books/interest.jpg',
        description:
            "Interstellar is a Christopher Nolan movie exploring the vast galaxy through a time and space paradox. The movie primarily focuses on life. Earth is coming to an end and a few astronauts are traveling to find another home at the end of the galaxy.",
        quantity: 1,
        doc_title: 'interesteller',
        doc_url: '',
        doc_date: '9-01-1019',
        page_num: 1),
    Product(
        id: 16,
        name: 'THE MATRIX',
        price: 370,
        category: 'NOVEL',
        image: 'assets/books/matrix1.jpg',
        description:
            "Groff's fourth novel, Matrix is about a seventeen-year-old Marie de France... sent to England to be the new prioress of an impoverished abbey, its nuns on the brink of starvation and beset by disease. Alex Preston, writing in The Observer, described it as a strange and poetic piece of historical fiction set in a dreamlike abbey, the fictional biography of a 12th-century mystic. Within the novel, Marie, whom Groff writes as a lesbian, turns around the abbey's fortunes and treats it as a quasi-mystical female separatist utopia",
        quantity: 1,
        doc_title: 'the matrix',
        doc_url: '',
        doc_date: '18-09-1911',
        page_num: 1),
    Product(
        id: 5,
        name: 'COCO',
        category: 'STORY',
        price: 100,
        image: 'assets/books/coco.jpg',
        description:
            'a 12-year-old Mexican boy named Miguel who journeys to the Land of the Dead to find his great-great grandfather, Ernesto de la Cruz, a legendary sing',
        quantity: 1,
        doc_title: 'coco',
        doc_url: '',
        doc_date: '09-08-1098',
        page_num: 1),
    Product(
        id: 6,
        name: 'BRAIN ON FIRE',
        price: 780,
        category: 'MYSTERY',
        image: 'assets/books/fire.jpg',
        description:
            "Brain on Fire: My Month of Madness is a 2012 New York Times best-selling autobiography by New York Post writer Susannah Cahalan. The book details Cahalan's struggle with a rare form of encephalitis and her recovery.",
        quantity: 1,
        doc_title: 'brain on fire',
        doc_url: '',
        doc_date: '13-09-2121',
        page_num: 1),
    Product(
        id: 7,
        name: 'MOTHER EARTH',
        price: 150,
        category: 'GENERIC',
        image: 'assets/books/earth1.jpg',
        description:
            "He explains how the earth was built from cosmic dust and transformed into continents, oceans, atmosphere, and life. We find out why earth was primed for life and the many ways it could have started. We learn how minerals and living organisms evolved together shaping the future of each other.",
        quantity: 3,
        doc_title: 'mother earth',
        doc_url: '',
        doc_date: '09-08-1919',
        page_num: 1),
    Product(
        id: 8,
        name: 'MAHABHARATHAM',
        price: 390,
        category: 'MYTHOLOGY',
        image: 'assets/books/Mahabharata.jpg',
        description:
            "The Mahabharata is an ancient Indian epic poem that is considered one of the most important texts in world literature. It is a narrative of the Kurukshetra War, a conflict between two groups of cousins, the Pandavas and the Kauravas, over the throne of Hastinapura. The epic also includes philosophical and devotional material, such as the Bhagavad Gita, and is considered a source of information on the development of Hinduism.",
        quantity: 1,
        doc_title: 'mahabharatam',
        doc_url: '',
        doc_date: '13-1909',
        page_num: 1),
    Product(
        id: 9,
        name: 'WORLD WAR II',
        price: 600,
        category: 'HISTORY',
        image: 'assets/books/world.jpg',
        description:
            "The Second World War is a 2012 narrative history of World War II by the British historian Antony Beevor. The book starts with the Japanese invasion of Manchuria in 1931, and covers the entire Second World War. It ends with the final surrender of Axis forces.",
        quantity: 1,
        doc_title: 'world war 2',
        doc_url: '',
        doc_date: '19-03-1202',
        page_num: 1),
    Product(
        id: 10,
        name: 'THE EXORIST',
        price: 570,
        category: 'NOVEL',
        image: 'assets/books/exorist1.jpg',
        description:
            "The Exorcist is a 1971 horror novel written by American writer William Peter Blatty and published by Harper & Row. The book details the demonic possession of eleven-year-old Regan MacNeil, the daughter of a famous actress, and the two priests who attempt to exorcise the demon.",
        quantity: 2,
        doc_title: 'exorist',
        doc_url: '',
        doc_date: '12-02-2022',
        page_num: 1),
    Product(
        id: 12,
        name: 'MOANA',
        category: 'story',
        price: 50,
        image: 'assets/books/moana.jpg',
        description:
            'As described by Gramma Tala, Moana "stands out from the crowd". She is sea-loving, headstrong, strong-willed, practically fearless, and physically capable. Though she has moments of self-doubt, she has great pride in who she is, and is generally too stubborn to back away from new challenges.',
        quantity: 1,
        doc_title: 'moana',
        doc_url: '',
        doc_date: '15-09-2099',
        page_num: 1),
    Product(
        id: 13,
        name: 'SHERK',
        category: 'anime',
        price: 80,
        image: 'assets/books/sherk.jpg',
        description:
            'Shrek is an anti-social and highly territorial ogre who loves the solitude of his swamp and enjoys fending off mobs and intruders. His life is interrupted after the dwarfish Lord Farquaad of Duloc exiles a vast number of fairy-tale creatures, who inadvertently end up in the swamp.',
        quantity: 1,
        doc_title: 'sherk',
        doc_url: '',
        doc_date: '13-9-1901',
        page_num: 1),
    Product(
        id: 14,
        name: 'UP',
        category: 'anime',
        price: 400,
        image: 'assets/books/up.jpg',
        description:
            'The film centers on Carl Fredricksen (Asner), an elderly widower who travels to South America with youngster Russell (Nagai) in order to fulfill a promise that he made to his late wife Ellie. In the jungle, they encounter an exotic bird and discover someone has sinister plans to capture it',
        quantity: 1,
        doc_title: 'up',
        doc_url: '',
        doc_date: '09-04-2029',
        page_num: 1),
    Product(
        id: 2,
        name: 'WALL-E',
        category: 'story',
        price: 200,
        image: 'assets/books/wall.jpg',
        description:
            'Mesmerized with trinkets of Earths history and show tunes, WALL-E is alone on Earth except for a sprightly pet cockroach. One day, EVE, a sleek (and dangerous) reconnaissance robot, is sent to Earth to find proof that life is once again sustainable. WALL-E falls in love with EVE.',
        quantity: 1,
        doc_title: 'wall e',
        doc_url: '',
        doc_date: '15-09-2004',
        page_num: 1),
  ];
// static List<Product>mycollection = [
//   Product(id: 1, name: 'THE REVENANT', category: 'NOVEL', image: 'assets/books/revenant.jpg', description: " A thrilling tale of betrayal and revenge set against the nineteenth-century American frontier, Michael Punke's The Revenant is the astonishing story of real-life trapper and frontiersman Hugh Glass. The year is 1823, and the trappers of the Rocky Mountain Fur Company live a brutalfrontier life.", quantity: 1,),
//   Product(id: 2, name: 'G O T', category: 'NOVEL', image: ' assets/books/got.jpg', description: "A Game of Thrones takes place over the course of one year on or near the fictional continent of Westeros. The story begins when King Robert visits the northern castle Winterfell to ask Ned Stark to be his right-hand assistant, or Hand of the King. The previous Hand, Jon Arryn, died under suspicious circumstances.", quantity: 1),
//   Product(id: 3, name: 'TANGLED', category: 'ADVENTURE', image:'assets/books/tangled1.jpg', description: "Rapunzel has spent her life locked in a tower, but that's not her only secret. Her long, golden hair has magical powers--all 70 feet of it! When the kingdom's most-wanted bandit unexpectedly stumbles into Rapunzel's tower, the pair embark on a fantastic journey that will uncover more than they ever expected.", quantity: 2),
//   Product(id: 3, name: 'IT', category: 'HORROR', image: 'assets/books/it1.jpg', description: "It is a horror novel by Stephen King about seven adults who return to their hometown to battle an evil creature that they first encountered as teenagers:", quantity: 3),
//   Product(id: 4, name: 'INTERESTELLAR', category: 'SCIENTIFIC', image: 'assets/books/interest.jpg', description: "Interstellar is a Christopher Nolan movie exploring the vast galaxy through a time and space paradox. The movie primarily focuses on life. Earth is coming to an end and a few astronauts are traveling to find another home at the end of the galaxy.", quantity:1),
//   Product(id: 5, name: 'THE MATRIX', category: 'NOVEL', image:'assets/books/matrix1.jpg' , description: "Groff's fourth novel, Matrix is about a seventeen-year-old Marie de France... sent to England to be the new prioress of an impoverished abbey, its nuns on the brink of starvation and beset by disease. Alex Preston, writing in The Observer, described it as a strange and poetic piece of historical fiction set in a dreamlike abbey, the fictional biography of a 12th-century mystic. Within the novel, Marie, whom Groff writes as a lesbian, turns around the abbey's fortunes and treats it as a quasi-mystical female separatist utopia", quantity: 1),
//   Product(id: 6, name: 'BRAIN ON FIRE', category: 'MYSTERY', image: 'assets/books/fire.jpg', description: "Brain on Fire: My Month of Madness is a 2012 New York Times best-selling autobiography by New York Post writer Susannah Cahalan. The book details Cahalan's struggle with a rare form of encephalitis and her recovery.", quantity: 1),
//   Product(id: 7, name: 'MOTHER EARTH', category: 'GENERIC', image: 'assets/books/earth1.jpg', description: "He explains how the earth was built from cosmic dust and transformed into continents, oceans, atmosphere, and life. We find out why earth was primed for life and the many ways it could have started. We learn how minerals and living organisms evolved together shaping the future of each other.", quantity: 3),
//   Product(id: 8, name: 'MAHABHARATHAM', category: 'MYTHOLOGY', image: 'assets/books/Mahabharata.jpg', description: "The Mahabharata is an ancient Indian epic poem that is considered one of the most important texts in world literature. It is a narrative of the Kurukshetra War, a conflict between two groups of cousins, the Pandavas and the Kauravas, over the throne of Hastinapura. The epic also includes philosophical and devotional material, such as the Bhagavad Gita, and is considered a source of information on the development of Hinduism.", quantity: 1),
//   Product(id: 9, name: 'WORLD WAR II', category: 'HISTORY', image: 'assets/books/world.jpg', description: "The Second World War is a 2012 narrative history of World War II by the British historian Antony Beevor. The book starts with the Japanese invasion of Manchuria in 1931, and covers the entire Second World War. It ends with the final surrender of Axis forces.", quantity: 1),
//   Product(id: 10, name: 'THE EXORIST', category: 'NOVEL', image: 'assets/books/exorist1.jpg', description: "The Exorcist is a 1971 horror novel written by American writer William Peter Blatty and published by Harper & Row. The book details the demonic possession of eleven-year-old Regan MacNeil, the daughter of a famous actress, and the two priests who attempt to exorcise the demon.", quantity: 2),
// ];
}
